nssm:register_mob("nssm:icelamander", {
	type = "monster",
	hp_max = 180,
	hp_min = 180,
	collisionbox = {-0.5, 0, -0.5, 0.5, 2.3, 0.5},
	visual = "mesh",
	mesh = "icelamander.x",
	textures = {{"icelamander.png"}},
	visual_size = {x=4, y=4},
	makes_footstep_sound = true,
	view_range = 35,
	lifetimer = 500,
	fear_height = 4,
	walk_velocity = 2,
	run_velocity = 4,
    sounds = {
		random = "icelamander",
	},
	damage = 8,
	jump = true,
	drops = {
                {name = "homedecor:coin",
                chance = 2,
                min = 5,
                max = 9,},
		{name = "nssm:frosted_amphibian_heart",
		chance = 1,
		min = 1,
		max = 1},
		{name = "default:mese_block",
		chance = 3,
		min = 1,
		max = 3,},
		{name = "default:diamond_block",
		chance = 3,
		min = 1,
		max = 3,},
		{name = "default:nyancat",
		chance = 3,
		min = 5,
		max = 9,},
    },
	armor = 30,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 30,
	light_damage = 0,
	on_rightclick = nil,
	dogshoot_stop = true,
	attack_type = "dogshoot",
	arrow = "nssm:snow_arrow",
	reach = 3,
	shoot_interval = 2,
	animation = {
		speed_normal = 15,
		speed_run = 25,
		stand_start = 1,
		stand_end = 40,
		walk_start = 80,
		walk_end = 160,
		run_start = 40,
		run_end = 80,
		punch_start = 160,
		punch_end = 190,
		dattack_start = 190,
		dattack_end = 210,
	},
	do_custom = function(self)
		nssm:midas_ability(self, "default:ice", self.run_velocity,1, 3)
	end,
})
