nssm:register_mob("nssm:larva", {
	type = "monster",
	hp_max = 10,
	hp_min = 8,
	collisionbox = {-0.3, 0, -0.3, 0.3, 0.41, 0.3},
	visual = "mesh",
	mesh = "larva.x",
	textures = {{"larva.png"}},
	visual_size = {x=3, y=3},
	makes_footstep_sound = false,
	view_range = 10,
	rotate = 90,
	jump = false,
	fear_height = 4,
	jump_height =0,
	walk_velocity = 0.4,
	run_velocity = 0.4,
    sounds = {
		random = "sand",
	},
	damage = 1,
	drops = {
                {name = "homedecor:coin",
                chance = 20,
                min = 1,
                max = 1,},
	},
	metamorphosis = true,
	armor = 100,
	drawtype = "front",
	water_damage = 2,
	lava_damage = 4,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	animation = {
		speed_normal = 20,
		speed_run = 20,
		stand_start = 0,
		stand_end = 80,
		walk_start = 100,
		walk_end = 160,
		run_start = 100,
		run_end = 160,
		punch_start = 180,
		punch_end = 230,
	}
})
