nssm:register_mob("nssm:moonheron", {
	type = "monster",
	hp_max = 23,
	hp_min = 22,
	collisionbox = {-0.45, -0.3, -0.45, 0.45, 0.3, 0.45},
	visual = "mesh",
	mesh = "moonheron.x",
	textures = {{"moonheron.png"}},
	visual_size = {x=10, y=10},
	view_range = 35,
	rotate = 270,
	walk_velocity = 2,
	run_velocity = 3,
  fall_speed = 0,
  stepheight = 3,
  sounds = {
		random = "moonheron",
		distance =40,
	},
	damage = 3,
	jump = true,
	drops = {
                {name = "homedecor:coin",
                chance = 9,
                min = 1,
                max = 2,},
		{name = "nssm:heron_leg",
		chance = 10,
		min = 1,
		max = 1,},
	},
	armor = 100,
	floats = 1,
	drawtype = "front",
	water_damage = 5,
	lava_damage = 5,
	light_damage=7,
	on_rightclick = nil,
  	fly = true,
	attack_type = "dogfight",
	animation = {
		speed_normal = 25,
		speed_run = 35,
		stand_start = 140,
		stand_end = 200,
		walk_start = 20,
		walk_end = 60,
		run_start = 20,
		run_end = 60,
		punch_start = 80,
		punch_end = 120,
	}
})
