nssm:register_mob("nssm:swimming_duck", {
	type = "monster",
	hp_max = 20,
	hp_min = 15,
	collisionbox = {-0.55, -0.30, -0.55, 0.55, 1, 0.55},
	visual = "mesh",
	mesh = "swimming_duck.x",
	textures = {{"swimming_duck.png"}},
	visual_size = {x=2, y=2},
	view_range = 15,
	floats=1,
	walk_velocity = 1,
	run_velocity = 1,
	damage = 2,
	jump = false,
	jump_chance = 0,
	jump_height = 0,
    sounds = {
		random = "duck",
	},
	drops = {
                {name = "homedecor:coin",
                chance = 10,
                min = 1,
                max = 1,},
		{name = "nssm:duck_legs",
		chance = 1,
		min = 1,
		max = 2,},
	},
	armor = 100,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 10,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	animation = {
		speed_normal = 25,
		speed_run = 35,
		stand_start = 1,
		stand_end = 60,
		walk_start = 80,
		walk_end = 120,
		run_start = 80,
		run_end = 120,
		punch_start = 140,
		punch_end = 160,
	}
})
