mobs:register_mob("nssm:chog", {
	type = "monster",
	hp_max = 25,
	hp_min = 21,
	collisionbox = {-0.4, 0, -0.4, 0.4, 1.4, 0.4},
	visual = "mesh",
	mesh = "chog.x",
	textures = {{"chog.png"}},
	visual_size = {x=4, y=4},
	makes_footstep_sound = true,
	view_range = 10,
	walk_velocity = 1,
	rotate = 270,
	fear_height = 4,
	run_velocity = 3.5,
	--[[sounds = {
		random = "chog",
	},]]
	damage = 1,
	jump = true,
	drops = {
		{name = "nssm:life_energy",
		chance = 1,
		min = 3,
		max = 4},
    },
	armor = 70,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 5,
	light_damage = 0,
	--group_attack=true,
	--attack_animals=true,
	knock_back=2,
	blood_texture="nssm_blood.png",
	stepheight=1.1,
	on_rightclick = nil,
	attack_type = "dogfight",
	animation = {
		speed_normal = 20,
		speed_run = 20,
		stand_start = 0,
		stand_end = 50,
		walk_start = 60,
		walk_end = 100,
		run_start = 110,
		run_end = 130,
		punch_start = 220,
		punch_end = 240,
    	shoot_start =170,
    	shoot_end=210,
		speed_die = 10,
		die_start = 140,
		die_end = 160,
    },
})
