mobs:register_mob("nssm:crystal_slug", {
	type = "monster",
	hp_max = 13,
	hp_min = 11,
	collisionbox = {-0.3, 0, -0.3, 0.3, 0.4, 0.3},
	visual = "mesh",
	mesh = "crystal_slug.x",
	textures = {{"crystal_slug.png"}},
	visual_size = {x=4, y=4},
	view_range = 40,
	floats=1,
	rotate = 270,
	group_attack=true,
	attack_animals=true,
	walk_velocity = 0.4,
	run_velocity = 0.4,
--	fall_speed = 0,
	stepheight = 1.1,
--[[	sounds = {
		random = "crystal_slug",
		distance = 45,
	},]]
	damage = 2,
	jump = false,
	drops = {
		{name = "nssm:life_energy",
		chance = 1,
		min = 1,
		max = 3,},
	},
	armor = 70,
	drawtype = "front",
	water_damage = 5,
	lava_damage = 10,
	light_damage = 0,
	blood_texture="nssm_blood_blue.png",
	blood_amount=10,
	on_rightclick = nil,
	attack_type = "shoot",
	shoot_offset = 1,
	arrow = "nssm:crystal_gas_arrow",
	reach = 1,
	shoot_interval = 2,
	animation = {
		speed_normal = 20,
		speed_run = 20,
		stand_start = 1,
		stand_end = 60,
		walk_start = 160,
		walk_end = 190,
		run_start = 160,
		run_end = 190,
		punch_start = 100,
		punch_end = 150,
		shoot_start = 100,
		shoot_end = 150,
		die_start = 70,
		die_end = 90,
	}
})
