mobs:register_mob("nssm:pelagia", {
	type = "monster",
	hp_max = 44,
	hp_min = 42,
	collisionbox = {-0.9, -0.5, -0.9, 0.9, 0.92, 0.9},
	visual = "mesh",
	mesh = "pelagia.x",
	textures = {{"pelagia.png"}},
	visual_size = {x=4, y=4},
	view_range =5,
	fly = true,
	fly_in = "default:water_source",
	fall_speed = -20,
	walk_velocity = 0.2,
	run_velocity = 1,
	damage = 6,
	reach = 1,
	rotate = 270,
	jump = false,
	jump_chance = 0,
	jump_height = 0,
	drops = {
			{name = "nssm:life_energy",
		chance = 1,
		min = 2,
		max = 7,},
	},
	armor = 100,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 10,
	light_damage = 0,
	group_attack=true,
	attack_animals=false,
	knock_back=4,
	blood_texture="nssm_blood_blue.png",
	on_rightclick = nil,
	attack_type = "dogfight",
	animation = {
		speed_normal = 25,
		speed_run = 35,
		stand_start = 1,
		stand_end = 80,
		walk_start = 1,
		walk_end = 80,
		run_start = 100,
		run_end = 120,
		punch_start = 140,
		punch_end = 180,
	}
})
