mobs:register_mob("nssm:pumpboom_small", {
	type = "monster",
	hp_max = 15,
	hp_min = 14,
	collisionbox = {-0.30, -0.3, -0.30, 0.30, 0.30, 0.30},
	visual = "mesh",
	mesh = "pumpboom.x",
	rotate = 270,
	textures = {{"pumpkid.png"}},
	visual_size = {x=2, y=2},
	explosion_radius = 2,
	makes_footstep_sound = true,
	view_range = 20,
	fear_height = 4,
	walk_velocity = 2,
	run_velocity = 2.5,
    sounds = {
    explode = "tnt_explode",
	random = "pumpboom",
	},
	damage = 1.5,
	jump = true,
	drops = {
		{name = "nssm:life_energy",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "nssm:black_powder",
		chance = 2,
		min = 1,
		max = 2,},
	},
	armor = 100,
	drawtype = "front",
	water_damage = 2,
	lava_damage = 5,
	light_damage = 0,
	group_attack=true,
	attack_animals=true,
	knock_back=2,
	blood_texture="nssm_blood.png",
	stepheight=1.1,
	on_rightclick = nil,
	attack_type = "explode",
	animation = {
		speed_normal = 20,
		speed_run = 20,
		stand_start = 1,
		stand_end = 30,
		walk_start = 81,
		walk_end = 97,
		run_start = 81,
		run_end = 97,
		punch_start = 70,
		punch_end = 80,
		die_start = 40,
		die_end = 60,
	}
})

mobs:register_mob("nssm:pumpboom_medium", {
	type = "monster",
	hp_max = 18,
	hp_min = 17,
	collisionbox = {-0.50, -0.3, -0.50, 0.50, 0.50, 0.50},
	visual = "mesh",
	mesh = "pumpboom.x",
	rotate = 270,
	textures = {{"pumpkid.png"}},
	visual_size = {x=4, y=4},
	makes_footstep_sound = true,
	view_range = 25,
	walk_velocity = 2,
	explosion_radius = 3,
	run_velocity = 2.5,
    sounds = {
    explode = "tnt_explode",
	random = "pumpboom",
	},
	damage = 1.5,
	jump = true,
	drops = {
		{name = "nssm:life_energy",
		chance = 1,
		min = 2,
		max = 3,},
		{name = "nssm:black_powder",
		chance = 2,
		min = 1,
		max = 3,},
	},
	armor = 100,
	drawtype = "front",
	water_damage = 2,
	lava_damage = 5,
	light_damage = 0,
	group_attack=true,
	attack_animals=true,
	knock_back=2,
	blood_texture="nssm_blood.png",
	stepheight=1.1,
	on_rightclick = nil,
	attack_type = "explode",
	animation = {
		speed_normal = 20,
		speed_run = 20,
		stand_start = 1,
		stand_end = 30,
		walk_start = 81,
		walk_end = 97,
		run_start = 81,
		run_end = 97,
		punch_start = 70,
		punch_end = 80,
		die_start = 40,
		die_end = 60,
	}
})

mobs:register_mob("nssm:pumpboom_large", {
	type = "monster",
	hp_max = 20,
	hp_min = 19,
	collisionbox = {-0.60, -0.3, -0.60, 0.60, 0.60, 0.60},
	visual = "mesh",
	mesh = "pumpboom.x",
	rotate = 270,
	explosion_radius = 5,
	textures = {{"pumpkid.png"}},
	visual_size = {x=6, y=6},
	makes_footstep_sound = true,
	view_range = 30,
	walk_velocity = 2,
	run_velocity = 3,
    sounds = {
    explode = "tnt_explode",
	random = "pumpboom",
	},
	damage = 1.5,
	jump = true,
	drops = {
		{name = "nssm:life_energy",
		chance = 1,
		min = 3,
		max = 4,},
		{name = "nssm:black_powder",
		chance = 2,
		min = 2,
		max = 4,},
	},
	armor = 100,
	drawtype = "front",
	water_damage = 2,
	lava_damage = 5,
	light_damage = 0,
	group_attack=true,
	attack_animals=true,
	knock_back=2,
	blood_texture="nssm_blood.png",
	stepheight=1.1,
	on_rightclick = nil,
	attack_type = "explode",
	animation = {
		speed_normal = 20,
		speed_run = 20,
		stand_start = 1,
		stand_end = 30,
		walk_start = 81,
		walk_end = 97,
		run_start = 81,
		run_end = 97,
		punch_start = 70,
		punch_end = 80,
		die_start = 40,
		die_end = 60,
	}
})
