mobs:register_mob("nssm:pumpkid", {
	type = "monster",
	hp_max = 13,
	hp_min = 11,
	collisionbox = {-0.4, 0, -0.4, 0.4, 1.5, 0.4},
	visual = "mesh",
	mesh = "pumpkid.x",
	textures = {{"pump.png"}},
	visual_size = {x=3, y=3},
	view_range = 30,
	floats=0,
	rotate = 180,
	group_attack=true,
	attack_animals=false,
	walk_velocity = 0.6,
	run_velocity = 0.6,
--	fall_speed = 0,
	stepheight = 1.1,
--[[	sounds = {
		random = "pumpkid",
		distance = 45,
	},]]
	damage = 2,
	jump = true,
	drops = {
		{name = "nssm:life_energy",
		chance = 1,
		min = 1,
		max = 3,},
	},
	armor = 50,
	drawtype = "front",
	water_damage = 5,
	lava_damage = 13,
	light_damage = 0,
	suffocation = 4,
	blood_texture="nssm_blood.png",
	blood_amount=10,
	on_rightclick = nil,
	attack_type = "shoot",
	shoot_offset = 1,
	arrow = "nssm:pumpkid_bomb",
	reach = 1,
	shoot_interval = 4,
	animation = {
		speed_normal = 20,
		speed_run = 20,
		stand_start = 0,
		stand_end = 40,
		walk_start = 60,
		walk_end = 100,
		run_start = 60,
		run_end = 100,
		punch_start = 110,
		punch_end = 210,
		shoot_start = 110,
		shoot_end = 210,
		die_start = 220,
		die_end = 240,
	}
})
