mobs:register_mob("nssm:salamander", {
	type = "monster",
	hp_max = 35,
	hp_min = 24,
	collisionbox = {-0.4, 0, -0.4, 0.4, 0.4, 0.4},
	visual = "mesh",
	rotate = 270,
	mesh = "salamander.x",
	textures = {{"salamander.png"}},
	visual_size = {x=10, y=10},
	fear_height = 4,
	makes_footstep_sound = true,
	view_range = 24,
	walk_velocity = 1,
	run_velocity = 2.2,
	damage = 6,
	jump = true,
	drops = {
		{name = "nssm:life_energy",
		chance = 1,
		min = 1,
		max = 2,},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 10,
	lava_damage = 0,
	light_damage = 0,
	group_attack=true,
	attack_animals=true,
	knock_back=2,
	blood_texture="nssm_blood.png",
	stepheight=1.1,
	on_rightclick = nil,
	dogshoot_switch = true,
	attack_type = "dogshoot",
    arrow = "nssm:lava_block_bomb",
    reach = 2,
    shoot_interval = 2,
    shoot_offset = 2,
	animation = {
		speed_normal = 25,
		speed_run = 35,
		stand_start = 0,
		stand_end = 80,
		walk_start = 110,
		walk_end = 150,
		run_start = 110,
		run_end = 150,
		punch_start = 160,
		punch_end = 180,
		shoot_start = 200,
		shoot_end = 250,
		die_start = 80,
		die_end = 100,
		--[[
		swim_start = 260,
		swim_end = 300,
		]]
	}
})
