mobs:register_mob("nssm:tartacacia", {
	type = "monster",
	hp_max = 36,
	hp_min = 27,
	collisionbox = {-2, 0, -2, 2, 3, 2},
	visual = "mesh",
	mesh = "tartacacia.x",
	textures = {{"tartacacia.png"}},
	visual_size = {x=10, y=10},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 0.6,
	rotate = 270,
	reach=10,
	fear_height = 4,
	run_velocity = 1.2,
	--[[sounds = {
		random = "tartacacia",
	},]]
	damage = 1,
	jump = true,
	drops = {
		{name = "nssm:life_energy",
		chance = 1,
		min = 3,
		max = 4},
    },
	armor = 70,
	drawtype = "front",
	water_damage = 2,
	lava_damage = 5,
	light_damage = 0,
	--group_attack=true,
	--attack_animals=true,
	knock_back=0,
	blood_texture="nssm_blood.png",
	stepheight=2.1,
	on_rightclick = nil,
	attack_type = "dogfight",
	specific_attack = {"player", "nssm:felucco"},
	animation = {
		speed_normal = 20,
		speed_run = 40,
		stand_start = 10,
		stand_end = 60,
		walk_start = 70,
		walk_end = 150,
		run_start = 70,
		run_end = 150,
		punch_start = 190,
		punch_end = 220,
		punch2_start = 230,
		punch2_end = 250,
		die_start = 160,
		die_end = 180,
    },
})
